# Generated by Django 5.2.17 on 2026-09-30 18:59

from django.db import migrations, models

import core.ids
from core.db.operations import EnableRLS


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_tenancy_functions"),
        ("organizations", "0002_alter_organization_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_key", models.CharField(max_length=300)),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("message-media", "Message Media"),
                            ("quote-pdf", "Quote Pdf"),
                            ("import", "Import"),
                            ("avatar", "Avatar"),
                            ("kb", "Kb"),
                            ("attachment", "Attachment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLEAN", "Clean"),
                            ("INFECTED", "Infected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_by_user_id", models.UUIDField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=models.Func(function="now", output_field=models.DateTimeField())
                    ),
                ),
            ],
            options={
                "db_table": "files",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "storage_key"), name="files_key_uq"
                    )
                ],
            },
        ),
        EnableRLS("File"),
        migrations.RunSQL(
            "ALTER TABLE files ADD CONSTRAINT files_organization_fk "
            "FOREIGN KEY (organization_id) REFERENCES organizations (id)",
            "ALTER TABLE files DROP CONSTRAINT IF EXISTS files_organization_fk",
        ),
        # ADR-008 §3: clave con la forma completa org/{tenant de la fila}/{purpose de la fila}/
        # yyyy/mm/{uuid} (sin nombres originales ni `..`) y valores cerrados en BD.
        migrations.RunSQL(
            "ALTER TABLE files ADD CONSTRAINT files_key_shape_ck CHECK (storage_key ~ ("
            "'^org/' || organization_id::text || '/' || purpose || "
            "'/[0-9]{4}/(0[1-9]|1[0-2])/"
            "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')), "
            "ADD CONSTRAINT files_values_ck CHECK (purpose IN ('message-media', 'quote-pdf', "
            "'import', 'avatar', 'kb', 'attachment') AND scan_status IN ('PENDING', 'CLEAN', "
            "'INFECTED') AND sha256 ~ '^[0-9a-f]{64}$')",
            "ALTER TABLE files DROP CONSTRAINT IF EXISTS files_key_shape_ck, "
            "DROP CONSTRAINT IF EXISTS files_values_ck",
        ),
    ]
