/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorFields } from "./errorFields";

export interface Error {
  /** Código estable. Lo único que decide el cliente. */
  code: string;
  /** Texto seguro para mostrar. */
  message?: string;
  /** Solo en VALIDATION_ERROR: errores por campo (`_`: generales). */
  fields?: ErrorFields;
}
