/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

/**
 * Solo en VALIDATION_ERROR: errores por campo (`_`: generales).
 */
export type ErrorFields = { [key: string]: unknown };
