/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { ScopesEnum } from "./scopesEnum";

export interface Grant {
  code: string;
  /** Alcances concedidos. Vacío si el permiso no admite alcance. */
  scopes: ScopesEnum[];
}
