/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

export interface LoginRequest {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /**
   * @minLength 1
   * @maxLength 1024
   */
  password: string;
}
