/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `OWN` - Own
 * * `TEAM` - Team
 * * `BRANCH` - Branch
 * * `ORGANIZATION` - Organization
 */
export type ScopesEnum = (typeof ScopesEnum)[keyof typeof ScopesEnum];

export const ScopesEnum = {
  OWN: "OWN",
  TEAM: "TEAM",
  BRANCH: "BRANCH",
  ORGANIZATION: "ORGANIZATION",
} as const;
