/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { Grant } from "./grant";
import type { MemberOrganization } from "./memberOrganization";
import type { MemberUser } from "./memberUser";
import type { RoleName } from "./roleName";

export interface SelfContext {
  user: MemberUser;
  organization: MemberOrganization;
  membership_id: string;
  /** Solo para mostrar: no autorizan nada. */
  roles: RoleName[];
  permissions: Grant[];
}
