# Generated by Django 5.2.17 on 2026-09-29 05:27

import uuid

import django.db.models.deletion
from django.db import migrations, models

from core.db.operations import CompositeTenantFK, EnableRLS, SecurityDefinerFunction


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_tenancy_functions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WidgetPart",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy_app.widget"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        EnableRLS("Widget"),
        EnableRLS("WidgetPart"),
        CompositeTenantFK(
            "WidgetPart", "widget", "Widget", name="tenancy_widgetpart_widget_org_fk"
        ),
        # Lookup cross-tenant mínimo para probar los requisitos de SECURITY DEFINER (T16).
        SecurityDefinerFunction(
            "tenancy_widget_organization",
            arguments="p_widget_id uuid",
            argtypes="uuid",
            returns="uuid",
            body="SELECT organization_id FROM public.tenancy_app_widget WHERE id = p_widget_id",
        ),
    ]
