# Generated by Django 5.2.17 on 2026-10-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="assigned_user_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="branch_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="created_by_user_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="team_id",
            field=models.UUIDField(null=True),
        ),
    ]
