# Generated by Django 5.2.17 on 2026-09-30 00:17

import django.core.serializers.json
from django.db import migrations, models

import core.ids
from core.db.operations import EnableRLS, SecurityDefinerFunction


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_org_sequences"),
        ("organizations", "0002_alter_organization_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("aggregate_type", models.CharField(max_length=50)),
                ("aggregate_id", models.UUIDField()),
                (
                    "payload",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_default=models.Func(function="now", output_field=models.DateTimeField())
                    ),
                ),
                ("published_at", models.DateTimeField(null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, default="", max_length=100)),
                ("correlation_id", models.CharField(max_length=64, null=True)),
            ],
            options={
                "db_table": "outbox_events",
                "indexes": [
                    models.Index(
                        condition=models.Q(("published_at__isnull", True)),
                        fields=["organization_id", "occurred_at", "id"],
                        name="outbox_events_pending_idx",
                    )
                ],
            },
        ),
        EnableRLS("OutboxEvent"),
        migrations.RunSQL(
            "ALTER TABLE outbox_events ADD CONSTRAINT outbox_events_organization_fk "
            "FOREIGN KEY (organization_id) REFERENCES organizations (id)",
            "ALTER TABLE outbox_events DROP CONSTRAINT IF EXISTS outbox_events_organization_fk",
        ),
        # Descubrimiento cross-tenant mínimo para el publisher (ADR-002 §3.3): solo IDs.
        SecurityDefinerFunction(
            "outbox_pending_organizations",
            arguments="p_limit integer",
            argtypes="integer",
            returns="SETOF uuid",
            # El tenant con el evento pendiente más antiguo primero: sin inanición.
            body="SELECT organization_id FROM public.outbox_events WHERE published_at IS NULL "
            "GROUP BY organization_id ORDER BY min(occurred_at) "
            "LIMIT greatest(1, least(p_limit, 1000))",
        ),
    ]
