# Generated by Django 5.2.17 on 2026-09-29 06:40

from django.db import migrations, models

import core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                default=core.ids.new_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
