# Generated by Django 5.2.17 on 2026-10-01 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.ids

T = "organization_memberships"
# ADR-002 §3.2: excepción controlada. Una política PERMISSIVE por comando; la rama por usuario
# del SELECT solo aplica SIN tenant activo. Esta tabla no lleva `tenant_isolation`.
ENABLE_RLS = f"""
ALTER TABLE {T} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {T} FORCE ROW LEVEL SECURITY;
CREATE POLICY memberships_select ON {T} FOR SELECT USING (
  CASE
    WHEN app_current_tenant() IS NOT NULL THEN organization_id = app_current_tenant()
    ELSE app_current_user() IS NOT NULL AND user_id = app_current_user()
  END
);
CREATE POLICY memberships_insert ON {T} FOR INSERT
  WITH CHECK (organization_id = app_current_tenant());
CREATE POLICY memberships_update ON {T} FOR UPDATE
  USING (organization_id = app_current_tenant())
  WITH CHECK (organization_id = app_current_tenant());
CREATE POLICY memberships_delete ON {T} FOR DELETE
  USING (organization_id = app_current_tenant());
"""
DISABLE_RLS = f"""
DROP POLICY IF EXISTS memberships_select ON {T};
DROP POLICY IF EXISTS memberships_insert ON {T};
DROP POLICY IF EXISTS memberships_update ON {T};
DROP POLICY IF EXISTS memberships_delete ON {T};
ALTER TABLE {T} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {T} DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_tenancy_functions"),
        ("organizations", "0002_alter_organization_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("DEACTIVATED", "Deactivated"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organization_memberships",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "user"),
                        name="organization_memberships_org_user_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["INVITED", "ACTIVE", "SUSPENDED", "DEACTIVATED"])
                        ),
                        name="organization_memberships_status_ck",
                    ),
                ],
            },
        ),
        migrations.RunSQL(  # FK de tenant de la primera tabla de negocio (OBS-F1-04-1)
            f"ALTER TABLE {T} ADD CONSTRAINT organization_memberships_organization_fk "
            "FOREIGN KEY (organization_id) REFERENCES organizations (id)",
            f"ALTER TABLE {T} DROP CONSTRAINT IF EXISTS organization_memberships_organization_fk",
        ),
        migrations.RunSQL(ENABLE_RLS, DISABLE_RLS),
    ]
