# Generated by Django 5.2.17 on 2026-10-01 08:25

from typing import Any

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models

import core.ids
from core.db.operations import CompositeTenantFK, EnableRLS


def tenant_fk(table: str) -> migrations.RunSQL:
    """FK de tenant de cada tabla (igual que `files`; OBS-F2-02-2)."""
    name = f"{table}_organization_fk"
    return migrations.RunSQL(
        f"ALTER TABLE {table} ADD CONSTRAINT {name} "
        "FOREIGN KEY (organization_id) REFERENCES organizations (id)",
        f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {name}",
    )


def revoke_runtime_writes(apps: Any, schema_editor: Any) -> None:
    """El catálogo es de solo lectura para el runtime: solo lo escribe el job de migraciones."""
    app_role = schema_editor.quote_name(settings.DB_APP_ROLE)
    schema_editor.execute(
        f"REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.permissions FROM {app_role}"
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_tenancy_functions"),
        ("organizations", "0004_membership_org_id_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("module", models.CharField(max_length=32)),
                ("is_sensitive", models.BooleanField()),
                ("supports_scope", models.BooleanField()),
            ],
            options={
                "db_table": "permissions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "supports_scope"), name="permissions_code_scope_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("code__regex", "^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$"),
                            models.Q(
                                ("code__regex", "\\.(own|team|branch|organization)$"), _negated=True
                            ),
                        ),
                        name="permissions_code_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_system", models.BooleanField(default=False)),
                ("is_owner_role", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "roles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "code"), name="roles_org_code_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization_id", "id"), name="roles_org_id_uq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_owner_role", True)),
                        fields=("organization_id",),
                        name="roles_one_owner_uq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MembershipRole",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="access.role",
                    ),
                ),
            ],
            options={
                "db_table": "membership_roles",
                "indexes": [
                    models.Index(
                        fields=["organization_id", "role"], name="membership_roles_org_role_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "membership", "role"),
                        name="membership_roles_membership_role_uq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("supports_scope", models.BooleanField(editable=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("OWN", "Own"),
                            ("TEAM", "Team"),
                            ("BRANCH", "Branch"),
                            ("ORGANIZATION", "Organization"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="permission_code",
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="access.permission",
                        to_field="code",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="access.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_permissions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "role", "permission"),
                        name="role_permissions_role_permission_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("scope__in", ["OWN", "TEAM", "BRANCH", "ORGANIZATION"]),
                                ("scope__isnull", False),
                                ("supports_scope", True),
                            ),
                            models.Q(("scope__isnull", True), ("supports_scope", False)),
                            _connector="OR",
                        ),
                        name="role_permissions_scope_ck",
                    ),
                ],
            },
        ),
        EnableRLS("Role"),
        EnableRLS("RolePermission"),
        EnableRLS("MembershipRole"),
        tenant_fk("roles"),
        tenant_fk("role_permissions"),
        tenant_fk("membership_roles"),
        # ADR-002 §4: FK compuestas con organization_id. La BD impide enlazar organizaciones
        # distintas (rol de B en una membresía o concesión de A), también con SQL directo.
        CompositeTenantFK("RolePermission", "role", "Role", name="role_permissions_role_org_fk"),
        CompositeTenantFK("MembershipRole", "role", "Role", name="membership_roles_role_org_fk"),
        migrations.RunSQL(  # la membresía es de otra app: CompositeTenantFK no cruza apps
            "ALTER TABLE membership_roles ADD CONSTRAINT membership_roles_membership_org_fk "
            "FOREIGN KEY (organization_id, membership_id) "
            "REFERENCES organization_memberships (organization_id, id)",
            "ALTER TABLE membership_roles "
            "DROP CONSTRAINT IF EXISTS membership_roles_membership_org_fk",
        ),
        # Fija `supports_scope` al valor del catálogo: junto al CHECK, el alcance es NULL si y
        # solo si el permiso no lo admite. Diferible para poder cambiarlo en una migración.
        migrations.RunSQL(
            "ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_permission_scope_fk "
            "FOREIGN KEY (permission_code, supports_scope) "
            "REFERENCES permissions (code, supports_scope) DEFERRABLE INITIALLY IMMEDIATE",
            "ALTER TABLE role_permissions "
            "DROP CONSTRAINT IF EXISTS role_permissions_permission_scope_fk",
        ),
        migrations.RunPython(revoke_runtime_writes, migrations.RunPython.noop),
    ]
